from sense_hat import SenseHat

sense = SenseHat()
sense.clear()

blue = (0,0,0)
red = (0,120,80)

sense.set_pixel(6,4,blue)
sense.set_pixel(6,5,blue)
sense.set_pixel(6,6,blue)
sense.set_pixel(6,7,blue)
sense.set_pixel(7,4,red)
sense.set_pixel(7,5,red)
sense.set_pixel(7,6,red)
sense.set_pixel(7,7,red)
sense.set_pixel(4,4,blue)
sense.set_pixel(4,5,blue)
sense.set_pixel(4,6,blue)
sense.set_pixel(4,7,blue)
sense.set_pixel(5,4,red)
sense.set_pixel(5,5,red)
sense.set_pixel(5,6,red)
sense.set_pixel(5,7,red)
sense.set_pixel(2,4,blue)
sense.set_pixel(2,5,blue)
sense.set_pixel(2,6,blue)
sense.set_pixel(2,7,blue)
sense.set_pixel(3,4,red)
sense.set_pixel(3,5,red)
sense.set_pixel(3,6,red)
sense.set_pixel(3,7,red)
sense.set_pixel(2,4,blue)
sense.set_pixel(2,5,blue)
sense.set_pixel(2,6,blue)
sense.set_pixel(2,7,blue)
sense.set_pixel(1,4,red)
sense.set_pixel(1,5,red)
sense.set_pixel(1,6,red)
sense.set_pixel(1,7,red)
sense.set_pixel(0,4,blue)
sense.set_pixel(0,5,blue)
sense.set_pixel(0,6,blue)
sense.set_pixel(0,7,blue)

sense.set_pixel(6,0,blue)
sense.set_pixel(6,1,blue)
sense.set_pixel(6,2,blue)
sense.set_pixel(6,3,blue)
sense.set_pixel(7,0,red)
sense.set_pixel(7,1,red)
sense.set_pixel(7,2,red)
sense.set_pixel(7,3,red)
sense.set_pixel(4,0,blue)
sense.set_pixel(4,1,blue)
sense.set_pixel(4,2,blue)
sense.set_pixel(4,3,blue)
sense.set_pixel(5,0,red)
sense.set_pixel(5,1,red)
sense.set_pixel(5,2,red)
sense.set_pixel(5,3,red)
sense.set_pixel(2,0,blue)
sense.set_pixel(2,1,blue)
sense.set_pixel(2,2,blue)
sense.set_pixel(2,3,blue)
sense.set_pixel(3,0,red)
sense.set_pixel(3,1,red)
sense.set_pixel(3,2,red)
sense.set_pixel(3,3,red)
sense.set_pixel(2,0,blue)
sense.set_pixel(2,1,blue)
sense.set_pixel(2,2,blue)
sense.set_pixel(2,3,blue)
sense.set_pixel(1,0,red)
sense.set_pixel(1,1,red)
sense.set_pixel(1,2,red)
sense.set_pixel(1,3,red)
sense.set_pixel(0,0,blue)
sense.set_pixel(0,1,blue)
sense.set_pixel(0,2,blue)
sense.set_pixel(0,3,blue)

